# See cmd/shell.go for definitions of these rate limits.
totalCertificates:
  window: 1h
  threshold: 100000
certificatesPerName:
  window: 1h
  threshold: 100000
registrationsPerIP:
  window: 1h
  threshold: 100000
pendingAuthorizationsPerAccount:
  window: 1h
  threshold: 100000
certificatesPerFQDNSet:
  window: 24h
  threshold: 100000
